version: "3"
services:
  web:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    container_name: 'apache2'
    ports:
      - 80:80
      - 443:443
    volumes:
      # Source
      - ../:/var/www
      # PHP ini
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      # Apache Site Configuration
      - ./config/apache2/conf:/etc/apache2/sites-enabled
      # TLS Certification Files
      - ./config/apache2/certs:/etc/apache2/certification
      # Apache Log Files
      - ../storage/logs/access.log:/var/log/apache2/access.log
      - ../storage/logs/error.log:/var/log/apache2/error.log
